
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button buttonDbTest;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.buttonDbTest = new global::Gtk.Button ();
		this.buttonDbTest.CanFocus = true;
		this.buttonDbTest.Name = "buttonDbTest";
		this.buttonDbTest.UseUnderline = true;
		this.buttonDbTest.Label = global::Mono.Unix.Catalog.GetString ("Testa databas");
		this.fixed1.Add (this.buttonDbTest);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.buttonDbTest]));
		w1.X = 121;
		w1.Y = 83;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonDbTest.Clicked += new global::System.EventHandler (this.OnButtonDbTestClicked);
	}
}
